server:
	port: ${vcap.application.port:8761} # Http Port

eureka:
	instance:
		hostname: localhost
	client:
		registerWithEureka: false
		fetchRegistry: false
	server:
		waitTimeInMsWhenSyncEmpty: 0

spring:
	thymeleaf:
		enabled: false # Disable Thymeleaf
